### ISSUE TITLE
docs: add example with custom options

### ISSUE THREAD

**Issue by tsivinsky** [tsivinsky/use-confirm#10]

**Comment by Prooksius** [comment]
`// src/components/ConfirmDialog.tsx
import { Modal } from "some-modal"; // really any modal, doesn't matter
import { useConfirm } from "@/lib/useConfirm";

export const ConfirmDialog = () => {
  const { isAsking, message, options, deny, confirm } = useConfirm();

  return (
    <Modal isOpen={isAsking} onClose={deny}>
      <div>{message}</div>
      <div>
        <button onClick={deny}>{options.buttonDeny ? options.buttonDeny : 'deny'}</button>
        <button onClick={confirm}>{options.buttonConfirm ? options.buttonConfirm : 'confirm'}</button>
      </div>
    </Modal>
  );
};`

`// usage anywere in app:
import { useConfirm } from "@/lib/useConfirm";

const Component = () => {
  const { ask } = useConfirm();

  const handleAction = async () => {
    const ok = await ask("wanna continue?", {buttonDeny: "deny", buttonConfirm: "confirm"});
    if (!ok) return;

    alert("Let's go!");
  };

  return (
    <div>
      <h1>hi mom</h1>
      <button onClick={handleAction}>do the action</button>
    </div>
  );
};`

**Comment by Prooksius** [comment]
`
  const handleAction = async () => {
    const ok = await ask("wanna continue?", {buttonDeny: "Cancel", buttonConfirm: "OK!!!"});
    if (!ok) return;

    alert("Let's go!");
  };
`

And, for instance, in src/components/ConfirmDialog.tsx you can read these buttons and use them instead of static texts "deny" and "confirm"
