### ISSUE TITLE
purpose of creating own provider and hook?

### ISSUE THREAD

**Issue by wallpants** [tsivinsky/use-confirm#11]
Hey man, great work and nice npm name.

I was trying to build something similar and found your package. I was unable to get it to work in a project, because of typescript complaining about your module's types not being accessible or something. I ended up pretty much copying your project and removing some parts that I didn't understand.

https://github.com/wallpants/use-confirm-hook

I got my project working just like I needed, but I removed the factories you included, because I didn't really understand what their purpose was. Any chance you can explain what they're for?

Thanks in advance if you do take the time to respond.

**Comment by tsivinsky** [comment]
Hey, thanks. I looked at your repo and you're right, you can remove factories and use hook this way, but you will unable to pass custom options to confirm dialog. I added `createConfirm` function with 2 factories for hook and provider so user could also pass options to modal if they needed to. Maybe there is a better way, but I didn't find it.

As for typescript errors, i don't know much, maybe there we some changes in newer versions that break something here. I honestly don't know.

**Comment by wallpants** [comment]
Thank you
